name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Inflate keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > webasyst-x/keystore.jks
      - name: Create webasyst.properties
        run: |
          echo "webasyst.x.client_id=\"${{ secrets.WEBASYST_X_CLIENT_ID_PROD }}\"" > webasyst.properties
          echo "webasyst.x.host=\"https://www.webasyst.com\"" >> webasyst.properties
      - name: Build APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          WEBASYST_X_RELEASE_KEY_PASSWORD: ${{ secrets.WEBASYST_X_RELEASE_KEY_PASSWORD  }}
        run: bash ./gradlew :webasyst-x:assembleRelease --stacktrace
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Rename APK
        run: mv webasyst-x/build/outputs/apk/release/webasyst-x-release.apk webasyst-x/build/outputs/apk/release/webasyst-x-${{ steps.get_tag_name.outputs.VERSION }}.apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: webasyst-x-${{ steps.get_tag_name.outputs.VERSION }}.apk
          path: webasyst-x/build/outputs/apk/release/webasyst-x-${{ steps.get_tag_name.outputs.VERSION }}.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          assets=()
          for asset in ./webasyst-x-*.apk/*.apk; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "${{ steps.get_tag_name.outputs.VERSION }}" "${{ steps.get_tag_name.outputs.VERSION }}"
